[tool.black]
line-length = 100
target-version = ["py37"]
include = ".pyi?$"
exclude = """
(
  /(
      .eggs         # exclude a few common directories in the
    | .git          # root of the project
    | .hg
    | .mypy_cache
    | .tox
    | .venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
"""

[tool.isort]
# compatible with psf/black
# https://github.com/psf/black/blob/master/docs/compatible_configs.md
force_grid_wrap = 0
include_trailing_comma = true
line_length = 100
multi_line_output = 3
not_skip = "__init__.py"
use_parentheses = true
